toc:
  - name: spark-js-sdk
    file: ciscospark.md
  - CiscoSpark
  - name: Calling
  - Phone
  - Call
  - name: Resources
    description: |
      These are the resources provided by CiscoSpark instances for interacting with our [developer API](https://developer.ciscospark.com/getting-started.html)
  - Memberships
  - Messages
  - People
  - Rooms
  - Teams
  - TeamMemberships
  - Webhooks
  # - Organizations
  # - Licenses
  # - Roles
  - name: Types
    description: |
      The following typedefs describes the responses of the above methods above
  - Types~Membership
  - Types~Message
  - Types~Room
  - Types~Team
  - Types~TeamMembership
  - Types~Webhook
